platform :ios, '8.1'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
    pod 'SlideMenuControllerSwift'
    pod 'IQKeyboardManagerSwift'
    pod 'PKHUD'
    pod 'Localize-Swift', '~> 1.1'
    pod 'Cosmos', '~> 7.0'
    pod 'Cloudinary'
    pod 'BSImagePicker'
    pod 'SwiftyJSON'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'AWSAutoScaling'
    pod 'AWSCloudWatch'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSElasticLoadBalancing'
    pod 'AWSIoT'
    pod 'AWSKinesis'
    pod 'AWSLambda'
    pod 'AWSLex'
    pod 'AWSMachineLearning'
    pod 'AWSMobileAnalytics'
    pod 'AWSPinpoint'
    pod 'AWSPolly'
    pod 'AWSRekognition'
    pod 'AWSS3'
    pod 'AWSSES'
    pod 'AWSSimpleDB'
    pod 'AWSSNS'
    pod 'AWSSQS'
    pod 'SDWebImage', '~>3.8'
    pod 'SDWebImage/WebP'
end

target ‘ProviDesk’ do
    shared_pods
end
